# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from form2 import TableList

class FileIO:

    def __init__(self, addr):
        self.addr = addr

    def readIO(self):
        f1 = open(self.addr, "tr")
        output = f1.read()
        f1.close()
        return output

    def writeIO(self, str1):
        f1 = open(self.addr, "ta")
        f1.write(str1+"\n")
        f1.close()


class Ui_Window2(QtWidgets.QWidget):
    def __init__(self):
        super().__init__()
        self.title = 'PyQt5 - QTableWidget'
        self.left = 0
        self.top = 0
        self.width = 300
        self.height = 200

        self.setWindowTitle(self.title)
        self.setGeometry(self.left, self.top, self.width, self.height)

    
    def createTable(self):
        data_list = fileio.readIO().splitlines()

        self.tableWidget = QtWidgets.QTableWidget()

        # Row co

        # Table will fit the screen horizontally
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.horizontalHeader().setSectionResizeMode(
            QtWidgets.QHeaderView.Stretch)

    
    def setupUi(self):

        self.createTable()

        self.layout = QtWidgets.QVBoxLayout()
        self.layout.addWidget(self.tableWidget)
        self.setLayout(self.layout)
        self.show()

class Ui_MainWindow(object):
    
    def showinfo(self):
        self.t1=TableList()
        self.t1.show()
        #sys.exit(t1.exec_())

    def clear_click(self):
        self.line_fname.clear()
        self.line_lname.clear()
        self.line_mail.clear()
        self.line_phone.clear()
        self.text_address.clear()
        #self.radio_male.setChecked(False)
        #self.radio_female.setChecked(False)
        self.checkbox_married.setChecked(False)
        self.spin_age.setValue(0)
        
        
    def submit_click(self):
        fname = self.line_fname.text()
        lname = self.line_lname.text()
        mail = self.line_mail.text()
        phone = self.line_phone.text()
        addr = self.text_address.toPlainText()
        gender = True if self.radio_male.isChecked() else False
        age=self.spin_age.value()
        married=self.checkbox_married.isChecked()
        fileio.writeIO(
            f"{fname},{lname},{mail},{phone},{addr},{gender},{age},{married}")
        self.clear_click()
        
        
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(458, 598)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setToolTip("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(4, 31, 453, 514))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.line_fname = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_fname.setFont(font)
        self.line_fname.setObjectName("line_fname")
        self.horizontalLayout_5.addWidget(self.line_fname)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.line_lname = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_lname.setFont(font)
        self.line_lname.setObjectName("line_lname")
        self.horizontalLayout_6.addWidget(self.line_lname)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_7.addWidget(self.label_3)
        self.line_mail = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_mail.setFont(font)
        self.line_mail.setObjectName("line_mail")
        self.horizontalLayout_7.addWidget(self.line_mail)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.text_address = QtWidgets.QTextEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_address.sizePolicy().hasHeightForWidth())
        self.text_address.setSizePolicy(sizePolicy)
        self.text_address.setMaximumSize(QtCore.QSize(16777215, 16000000))
        self.text_address.setObjectName("text_address")
        self.verticalLayout.addWidget(self.text_address)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.line_phone = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.line_phone.setFont(font)
        self.line_phone.setObjectName("line_phone")
        self.horizontalLayout_4.addWidget(self.line_phone)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.radio_male = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radio_male.setFont(font)
        self.radio_male.setObjectName("radio_male")
        self.horizontalLayout_3.addWidget(self.radio_male)
        self.radio_female = QtWidgets.QRadioButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.radio_female.setFont(font)
        self.radio_female.setObjectName("radio_female")
        self.horizontalLayout_3.addWidget(self.radio_female)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.spin_age = QtWidgets.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.spin_age.setFont(font)
        self.spin_age.setObjectName("spin_age")
        self.horizontalLayout_2.addWidget(self.spin_age)
        self.checkbox_married = QtWidgets.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.checkbox_married.setFont(font)
        self.checkbox_married.setObjectName("checkbox_married")
        self.horizontalLayout_2.addWidget(self.checkbox_married)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_submit = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_submit.setFont(font)
        self.btn_submit.setStyleSheet("")
        self.btn_submit.setObjectName("btn_submit")
        self.horizontalLayout.addWidget(self.btn_submit)
        self.btn_cancel = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_cancel.setFont(font)
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout.addWidget(self.btn_cancel)
        self.btn_clear = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_clear.setFont(font)
        self.btn_clear.setObjectName("btn_clear")
        self.horizontalLayout.addWidget(self.btn_clear)
        self.btn_showinfo = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.btn_showinfo.setFont(font)
        self.btn_showinfo.setObjectName("btn_showinfo")
        self.horizontalLayout.addWidget(self.btn_showinfo)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 458, 24))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.btn_submit.clicked.connect(self.submit_click)  # type: ignore
        self.btn_clear.clicked.connect(self.clear_click)  # type: ignore
        self.btn_cancel.clicked.connect(MainWindow.close)  # type: ignore
        self.btn_showinfo.clicked.connect(self.showinfo)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.line_fname, self.line_lname)
        MainWindow.setTabOrder(self.line_lname, self.line_mail)
        MainWindow.setTabOrder(self.line_mail, self.text_address)
        MainWindow.setTabOrder(self.text_address, self.line_phone)
        MainWindow.setTabOrder(self.line_phone, self.spin_age)
        MainWindow.setTabOrder(self.spin_age, self.checkbox_married)
        MainWindow.setTabOrder(self.checkbox_married, self.btn_submit)
        MainWindow.setTabOrder(self.btn_submit, self.btn_cancel)
        MainWindow.setTabOrder(self.btn_cancel, self.btn_clear)
        MainWindow.setTabOrder(self.btn_clear, self.btn_showinfo)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Register Form"))
        self.label.setText(_translate("MainWindow", "FirstName:"))
        self.label_2.setText(_translate("MainWindow", "LastName:"))
        self.label_3.setText(_translate("MainWindow", "Email          "))
        self.label_4.setText(_translate("MainWindow", "Address"))
        self.text_address.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-weight:296;\"><br /></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "Phone:       "))
        self.label_5.setText(_translate("MainWindow", "Gender:"))
        self.radio_male.setText(_translate("MainWindow", "Male"))
        self.radio_female.setText(_translate("MainWindow", "Female"))
        self.label_6.setText(_translate("MainWindow", "Age:"))
        self.checkbox_married.setText(_translate("MainWindow", "married"))
        self.btn_submit.setText(_translate("MainWindow", "Submit"))
        self.btn_cancel.setText(_translate("MainWindow", "Cancel"))
        self.btn_clear.setText(_translate("MainWindow", "Clear"))
        self.btn_showinfo.setText(_translate("MainWindow", "ShowInfo"))
        self.menu.setTitle(_translate("MainWindow", "فرم ثبت نام"))


if __name__ == "__main__":
    fileio = FileIO("/Users/alireza/Desktop/pyadv-02/session-10/data.txt")
    import sys
    
    app = QtWidgets.QApplication(sys.argv)
    
    
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    
    sys.exit(app.exec_())
