# Form implementation generated from reading ui file '/Users/alireza/Desktop/pyadv-02/session-12/MusicPlayer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 461)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.slider_music = QtWidgets.QSlider(parent=self.centralwidget)
        self.slider_music.setGeometry(QtCore.QRect(20, 150, 661, 22))
        self.slider_music.setProperty("value", 10)
        self.slider_music.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.slider_music.setObjectName("slider_music")
        self.btn_v_up = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_v_up.setGeometry(QtCore.QRect(70, 230, 151, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_v_up.sizePolicy().hasHeightForWidth())
        self.btn_v_up.setSizePolicy(sizePolicy)
        self.btn_v_up.setObjectName("btn_v_up")
        self.btn_v_down = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_v_down.setGeometry(QtCore.QRect(240, 230, 151, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_v_down.sizePolicy().hasHeightForWidth())
        self.btn_v_down.setSizePolicy(sizePolicy)
        self.btn_v_down.setObjectName("btn_v_down")
        self.btn_play = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_play.setGeometry(QtCore.QRect(420, 230, 151, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_play.sizePolicy().hasHeightForWidth())
        self.btn_play.setSizePolicy(sizePolicy)
        self.btn_play.setObjectName("btn_play")
        self.btn_stop = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(590, 230, 151, 151))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_stop.sizePolicy().hasHeightForWidth())
        self.btn_stop.setSizePolicy(sizePolicy)
        self.btn_stop.setObjectName("btn_stop")
        self.btn_open = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btn_open.setGeometry(QtCore.QRect(690, 110, 101, 91))
        self.btn_open.setObjectName("btn_open")
        self.label_music = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_music.setGeometry(QtCore.QRect(50, 40, 641, 41))
        font = QtGui.QFont()
        font.setFamily(".Apple SD Gothic NeoI")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.label_music.setFont(font)
        self.label_music.setObjectName("label_music")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_v_up.setText(_translate("MainWindow", "Volume Up"))
        self.btn_v_down.setText(_translate("MainWindow", "Volume Down"))
        self.btn_play.setText(_translate("MainWindow", "Play"))
        self.btn_stop.setText(_translate("MainWindow", "Stop"))
        self.btn_open.setText(_translate("MainWindow", "open"))
        self.label_music.setText(_translate("MainWindow", "!!"))
